import type { CSSProperties } from 'react'

/**
 * Подсветка как в Cursor / VS Code Dark+.
 * Без фонов на токенах — иначе блок выглядит «выделенным».
 */
export const cursorCodeTheme: Record<string, CSSProperties> = {
  'code[class*="language-"]': {
    color: '#d4d4d4',
    background: 'none',
    fontFamily: 'var(--font-mono)',
    fontSize: '0.9rem',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: 1.55,
    tabSize: 2,
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: '#d4d4d4',
    background: 'transparent',
    fontFamily: 'var(--font-mono)',
    fontSize: '0.9rem',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: 1.55,
    tabSize: 2,
    hyphens: 'none',
    margin: 0,
    padding: 0,
    overflow: 'auto',
  },
  'pre[class*="language-"]::selection': {
    background: '#264f78',
  },
  'pre[class*="language-"] ::selection': {
    background: '#264f78',
  },
  'code[class*="language-"]::selection': {
    background: '#264f78',
  },
  'code[class*="language-"] ::selection': {
    background: '#264f78',
  },
  comment: { color: '#6a9955' },
  prolog: { color: '#6a9955' },
  doctype: { color: '#6a9955' },
  cdata: { color: '#6a9955' },
  punctuation: { color: '#d4d4d4' },
  namespace: { color: '#4ec9b0' },
  property: { color: '#9cdcfe' },
  tag: { color: '#569cd6' },
  boolean: { color: '#569cd6' },
  number: { color: '#b5cea8' },
  constant: { color: '#569cd6' },
  symbol: { color: '#b5cea8' },
  deleted: { color: '#ce9178' },
  selector: { color: '#d7ba7d' },
  'attr-name': { color: '#9cdcfe' },
  string: { color: '#ce9178' },
  char: { color: '#ce9178' },
  builtin: { color: '#4ec9b0' },
  inserted: { color: '#b5cea8' },
  operator: { color: '#d4d4d4' },
  entity: { color: '#d4d4d4', cursor: 'help' },
  url: { color: '#ce9178' },
  '.language-css .token.string': { color: '#ce9178' },
  '.style .token.string': { color: '#ce9178' },
  atrule: { color: '#c586c0' },
  'attr-value': { color: '#ce9178' },
  keyword: { color: '#569cd6' },
  function: { color: '#dcdcaa' },
  'class-name': { color: '#4ec9b0' },
  regex: { color: '#d16969' },
  important: { color: '#569cd6', fontWeight: 'bold' },
  variable: { color: '#9cdcfe' },
  parameter: { color: '#9cdcfe' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
}
